### ISSUE TITLE
Logo cannot be updated

### ISSUE THREAD

**Issue by GhaziTriki** [Leantime/leantime#106]
I tried updating the logo in 2.0.8 and it seems that it does not work anymore.

**Comment by marcelfolaron** [comment]
Thanks for testing! 
Do you see any error messages? Is this on local upload or S3? 
So far I haven't been able to reproduce it.

**Comment by GhaziTriki** [comment]
No error message, it is local.

**Comment by marcelfolaron** [comment]
I noticed every once in a while you have to click twice on the save button to save the image. I'll investigate that some more. Is that the issue you are seeing as well?

**Comment by dejanmeznarc** [comment]
You need to have write permission to change logo.

**Comment by marcelfolaron** [comment]
New tracking bug to combine multiple issues. Please see #112

**Comment by stijn-uva** [comment]
I have the same issue. The permissions on both `/userfiles` and `/public/userfiles` are 777. When uploading a new logo I get a "Success! Company settings edited successfully" notice but the logo does not change. No file is created in either userfiles folder. I am running Leantime via Apache.

This seems unrelated to #112 as that concerns the `downloading` of files whereas this involves a failure while `uploading` one.

Please let me know if there is any other info you require.

**Comment by rpacheco2019** [comment]
Hello @stijn-uva , I'm using version 2.1.1 and the upload logo is working fine. Also have PHP 7.2 and Apache. Can you confirm the user / group for the folder project? for apache must be www-data:www-data. Also just for curiosity , can you change the photo of the user's avatar?

@marcelfolaron , sorry i'm new to github. I don't really know if is good to comment a closed ticket. 👍

**Comment by stijn-uva** [comment]
The user was `root:www-data`, but changing it to `www-data:www-data` makes no difference.

Changing my avatar works fine, actually! This gave me an idea - the issue was with the image, rather than the upload routine itself. When I tried changing the logo to another image than I originally tested with, it failed silently as indicated above. I don't know what's causing it exactly, but this image fails every time I try uploading it as the logo:

![test-logo](https://user-images.githubusercontent.com/42036349/81721376-1064fd00-9480-11ea-937f-0f7a642fdca3.png)

As noted, I can use this image as my avatar. It's just when uploading it as a logo that it fails.

@marcelfolaron should I create a new issue for this?

**Comment by marcelfolaron** [comment]
Hi, thanks. Yes please create a new issue. I'll have to check why this
image fails particularly. Instead of adding it here, can you send me the
original file to support@leantime.io?

Sincerely,
Marcel

**Comment by big1tasty** [comment]
Hi, i also cannot change the logo in leantime, i just installed it with docker compose changed no lines really exept passwords. When i try to upload a different logo 260 x 60 px in png or jpg and press save it closes and nothing happens.
i'm relatively new to docker so sorry if i do something wrong when not changing the docke compose file?
i tried local and via domain behind reverse proxy

**Comment by marcelfolaron** [comment]
Hey,

Can you open a new issue. Almost missed this comment since it's on a closed issue. Can you check and see if there are any errors in resources/logs/error.log in your docker container?

**Comment by big1tasty** [comment]
hey, thank you, i created a new issue https://github.com/Leantime/leantime/issues/1145
