### ISSUE TITLE
[BUG] Card height is unnecessarly high

### ISSUE THREAD

**Issue by Pheggas** [Leantime/leantime#1070]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
In the few latest updates (it wasn't present on 2.2.8 version and in 2.2.10 is), the card height appear to be the same regardless on lenght of the text.

**To Reproduce**
1. Create card
2. See bug

**Expected behavior**
Same behaviour as in 2.2.8.

**Leantime Version**
2.2.10

**Server**
-

**PHP / MySQL Version**
MySQL

**Additional context**
![image](https://user-images.githubusercontent.com/9994511/197324063-e8c82073-7e63-4435-9f83-431f0a7b7d4c.png)

**Comment by diderich** [comment]
**Question:** Should all the tasks have the same height?
**Answer A:** If so, then I think the current approach/appearance is sound?
**Answer B:** If not, making the following changes would lead to what I would find an appealing layout:
```patch
diff --git a/public/css/components/kanban.css b/public/css/components/kanban.css
index 44fc05c8..ad09f1d4 100644
--- a/public/css/components/kanban.css
+++ b/public/css/components/kanban.css
@@ -266,7 +266,7 @@ body .maincontent .priority-bg-5 {
 
 .kanbanContent {
     overflow:hidden;
-    height:75px;
+    max-height:75px;
     position:relative;
 }
 
@@ -278,4 +278,4 @@ body .maincontent .priority-bg-5 {
     left: 0;
     bottom: 0;
     background: linear-gradient(transparent, var(--kanban-card-bg) 70% 100%);
-}
\ No newline at end of file
+}
diff --git a/src/domain/tickets/templates/showKanban.tpl.php b/src/domain/tickets/templates/showKanban.tpl.php
index 667deaf9..d3634830 100644
--- a/src/domain/tickets/templates/showKanban.tpl.php
+++ b/src/domain/tickets/templates/showKanban.tpl.php
@@ -288,7 +288,7 @@
                                                 <?php } ?>
                                                 <small><i class="fa <?php echo $todoTypeIcons[strtolower($row['type'])]; ?>"></i> <?php echo $this->__("label.".strtolower($row['type'])); ?></small>
                                                 <small>#<?php echo $row['id']; ?></small>
-                                                <div class="kanbanCardContent" style="margin-bottom:20px;">
+                                                <div class="kanbanCardContent">
 
                                                     <h4><a class='ticketModal' href="<?=BASE_URL ?>/tickets/showTicket/<?php echo $row["id"];?>"><?php $this->e($row["headline"]);?></a></h4>
 ```

As I do not want to speculate on the actual intent/answer to the question, I haven't offered the suggested change as a pull request.

**Comment by Pheggas** [comment]
Right. Maybe the change was made on purpose. Maybe the dev has so many same feedbacks on that he changed it. I mean, it's not like i consider it only as bug but it is change that isn't documented in releases or in commits.

**Comment by kevinreadFA** [comment]
change the kanban.css from height: 75px;  to  height:auto;
this would allow the box to follow content , unless this conflicts with another element in the new version

**Comment by marcelfolaron** [comment]
Hey all,

The goal is to keep card sizes uniform and the same height. Different
heights give tasks that may have lower priority but more content a visually
more importance which we are trying to avoid. With that said I see that the
tasks without any content include a lot of white space, so I’d suggest a
two potential options:

A make empty description boxes smaller but leave cards with description at
75px.

B. Create a project setting to toggle description visibility.
“On” all cards are 75px.
“off” no description is being shown.
“full content” everything is visible

**Comment by Pheggas** [comment]
> With that said I see that the tasks without any content include a lot of white space, so I’d suggest a two potential options: A make empty description boxes smaller but leave cards with description at 75px. B. Create a project setting to toggle description visibility. “On” all cards are 75px. “off” no description is being shown. “full content” everything is visible

For me it's always better to let the user customize it. So i choose B. Maybe we could do some kind of voting for this feature?

**Comment by diderich** [comment]
@marcelfolaron, I see your point that too large elements could have an impact on users implicitly prioritizing elements.
On the other hand, a lot of space is wasted if most elements contain limited to no text. And on laptops, screen space is limited (on a huge screen it would not matter).

- I would prefer a solution where the maximal height is limited (avoiding large elements), rather than a fixed height (see figure 3).
- I would be against adding another menu (like your option B) as it will further clutter the user interface!
- As a compromise, I could imagine a "hover" function that shows the full content when moving the cursor over the element (as shown in figure 4 and 5 below), either showing no text (as shown in figure 5 below), or a one line equal height solution [my preferred] (as shown in figure 4)

**Figure 1 - Current solution**: Lot of white space
![current](https://user-images.githubusercontent.com/10230144/197378540-56aadd3b-56bb-4472-9808-f40b9ad3e08c.jpg)

**Figure 2 - Full view**: The other extreme, too much info
![full](https://user-images.githubusercontent.com/10230144/197378577-880301a8-f342-47f5-b3ac-643b2b5b1967.jpg)

**Figure 3 - Height limited to 75px (for example)**: Compromise
![max-height](https://user-images.githubusercontent.com/10230144/197378590-eb7e3dfd-c9e7-4761-8a69-66ee43842fcc.jpg)

**Figure 4 - Pop-up with one line of text and equal height**: Trying to get the best of both worlds
![one line](https://user-images.githubusercontent.com/10230144/197378635-cd551459-baf4-4fa6-9223-99be56b50409.jpg)
![popup-one line](https://user-images.githubusercontent.com/10230144/197378725-b1e62226-05df-429b-9b56-63f42db4b9b9.jpg)

**Figure 5 - Pop-up with no text and equal height**: Another compromise solution
![no-text](https://user-images.githubusercontent.com/10230144/197378826-4697f286-741e-4e3f-ba66-ef4f12540919.jpg)
![popup-no-text](https://user-images.githubusercontent.com/10230144/197378728-64ae98ce-1cc0-4b8c-8b14-36678a429f6a.jpg)

**Comment by marcelfolaron** [comment]
I ended up pushing a fix to master that is in line with your first suggestion @diderich 
If there is no description the content container will not be shown (and thus the max/min height does not apply). If there is a description content is set to 75px. This ensures a relativley equal height between tasks

**Comment by S0und** [comment]
In a future update would you consider to allow the user to set a prefered card size? Exp. Detailed vs Compact

Even on 2.2.11, i still find the cards are unnecessary too big. On a 1080 screen, i can see 3 cards per screen. 

![image](https://user-images.githubusercontent.com/1266308/202449317-09da7eb7-2d32-4535-9e71-0cde9b7aebf6.png)

**Comment by marcelfolaron** [comment]
That looks like the old card size. Can you check and clear your cache? The
cards should look like the ones on the right side without a description.
