### ISSUE TITLE
Better mobile version

### ISSUE THREAD

**Issue by airikr-e** [Leantime/leantime#132]
Hi.

The mobile version of Leantime are quite bad.

- If the side panel are visible and you refreshing the page, the side panel will not hide by default.
- The Kanban are in the same position as on the desktop version. Suggestion: make them be under each other (for an example, `flex-direction: column;`).
- If the screen are between 481 and 554 pixels in width, the links on the top bar ("My Timesheets" & "My Calendar" & the log out icon) are over the header (for an example, "Overview, My Timesheets").
   - The links on the top bar overlaps the side panel link, making it impossible to get the side panel be active on some screen resolutions.

**Comment by marcelfolaron** [comment]
Hi, 
thanks for reaching out! 
Yes, the mobile version does need some work. Thank you for your suggestions, we are working on a fix.

**Comment by aschrijver** [comment]
Some more feedback about mobile (Android, Samsung S7, Firefox):

- The ToDo and Backlog pages are nearly unusable, because you cannot scroll down without touching cards, which will then be dragged instead. There should be more free space on the sides

- The My Calendar date text flows off-screen on the right, as well as the month / week / day buttons, and there is no way to reach them.

- Instead of a logout icon on the header menu, I'd rather have a dropdown menu with Logout in its choices. I accidentally clicked logout twice already, and this will avoid that.

**Comment by marcelfolaron** [comment]
We made some progress on the mobile view. The site is now at least usable again. More improvements to come.
