### ISSUE TITLE
[BUG] Can't edit Subtask details inside a To-Do

### ISSUE THREAD

**Issue by massimiliano-dalcero** [Leantime/leantime#1376]
Hello,
I tested both on Firefox and Chrome last versions.

When creating a SubTask inside a "To-Do", there is the button "quick add to-do"

![image](https://user-images.githubusercontent.com/5049867/216581366-bfe65ede-32a7-4397-a9df-75725fb85eca.png)

The sub task is created but there are two main bug issues:
- the sub task details is not editable, is possible only delete it or select options using bottom menus.

![image](https://user-images.githubusercontent.com/5049867/216581392-032a437b-b1cf-4bb4-bb17-2104d30ceb81.png)

Note that if go to url with the "ID" of sub-task, the edit windows appear. So the functionality exists, but is not triggerable using graphical interface. Eg:
http://192.168.226.128:8080/tickets/showTicket/$SUBTASK_ID

- the sub task created is ever editable, so in every moment is possible create an involontary alteration
![image](https://user-images.githubusercontent.com/5049867/216581412-b087b937-22b1-4880-ba64-b2b16261c845.png)

Note: 
"not clickable": is not possible going to details of subtask, is only possible edit it

Best Regards,
M.

**Comment by gloriafolaron** [comment]
Thanks for reporting this!

**Comment by v-marinkov** [comment]
Also, on 2.3.15 the CSS is messed up for the modal of the subtask:
![image](https://user-images.githubusercontent.com/7135724/232254521-d8b75b2e-65aa-4652-87be-eba73d416d5d.png)

This is easily fixed by removing the `position: fixed` on the individual links `<a></a>`s in the modal:
![image](https://user-images.githubusercontent.com/7135724/232254637-8404cbbd-cab0-4900-8120-c5deaad79869.png)
![image](https://user-images.githubusercontent.com/7135724/232254660-596a67cb-5bbf-448a-b645-dc038ac8f2f4.png)
