### ISSUE TITLE
[BUG] Kanban view shows editor placeholder text for ToDos

### ISSUE THREAD

**Issue by kav2k** [Leantime/leantime#1385]
**Describe the bug**
A ToDo with an empty description shows the editor placeholder text "Enter text or type '/' for commands or '@' to mention someone" in Kanban view card.
This only happens if the editor was never interacted with; clicking into the description editor then saving makes the description blank. Presumably there's a difference there between NULL and empty..

![Bugged ToDo card with placeholder text](https://user-images.githubusercontent.com/1549691/216954081-523f771f-e2f7-4369-90c0-8fc78c5cca4e.png)

**To Reproduce**
1. Create a fresh project
2. Go to ToDos tab
3. Add a new ToDo without ever touching the Description editor

**Expected behavior**
Expected no description text at all on the Kanban card:
![ToDo card with empty description](https://user-images.githubusercontent.com/1549691/216954356-80ab98d7-2b7d-4dc0-b95b-fc5ae0de6e3f.png)

**Leantime Version**
2.3.6

**Server**
Apache2 2.4.29 reverse proxy in front of Leantime container

**PHP / MySQL Version**
PHP 8.0.21 (Leantime docker container)
MySQL Ver 14.14 Distrib 5.7.41

**Additional context**
N/A

**Comment by kav2k** [comment]
This also affects display of descriptions in other places, e.g. a project with an empty description.
![Project dashboard with placeholder description](https://user-images.githubusercontent.com/1549691/217231237-a6c3d2bb-b0b7-4b51-bbd2-1e220b817c20.png)

**Comment by Ruakij** [comment]
@marcelfolaron 
The fix for this is not complete everywhere e.g. in the Ideas tab, a Discussion-comment can be saved without text.
The placeholder is properly removed, but an empty comment is posted regardless.

The placeholder isnt removed for replies on comments.

![image](https://user-images.githubusercontent.com/54639830/220592792-874e68f8-36f7-4be2-a40d-8df55c51cdea.png)

Same is true for other comment-areas like To-Dos.
Also, trying to post a comment in ToDos wont post it, but a loader appears regardless, couldnt the client check itself if it can press the button and enable/disable it once text was entered/removed?

Is the frontend using some kind of Framework with components like Vuejs or Angular? Would be easiest as these components are the same everywhere anyways, so a fix would be universal?
