### ISSUE TITLE
[BUG] Unable to set a new avatar image

### ISSUE THREAD

**Issue by sbamamoto** [Leantime/leantime#1485]
I am unable to upload an avatar image.

1. Go to Profile
2. Click on Upload File
3. Select an image file
4. The image will be displayed in the preview window
5. Scale and select move the image until it matches your preferences
6. Click on Save.
7. The image is lost.

The image should be displayed as selected.

I am using Leantime 2.3.11 and 2.3.13 / docker.

**Comment by marcelfolaron** [comment]
I was not able to reproduce this issue. Is it a specific file type that is causing this issue?

**Comment by charly-palencia** [comment]
Same bug here using docker-compose and S3 bucket. The upload images from Tasks and docs are working as expected, but the image is like crash all the time. 

Actual behavior 
1. go to profile page 
2. upload a new image in the profile picture section 
3. press upload.
4. the profile image looks broken (IMG url goes to `api/users?profileImage=1`)
5. Image is uploaded to s3 bucket. 
6. refresh (shift+cmd+r)

Expected behavior
4. Show profile picture. 

![image](https://github.com/Leantime/leantime/assets/645526/a37253d5-5d52-4159-8e38-b0122c24018e)

**Comment by charly-palencia** [comment]
please @marcelfolaron could you reopen this issue? thanks!!
