### ISSUE TITLE
install instructions for dummies

### ISSUE THREAD

**Issue by herrvonvoid** [Leantime/leantime#1688]
Hi, I'm having a really hard time installing this as I am not very
familiar with docker, servers and networks. It got even more complicated
because I just want to use this personally on my pc, not on a server: I
try not to compromise my machine with servers open to the internet or
containers running with root access.

After failing to host it myself in a vm, I installed it in the vm
following the docker instructions which worked - but when i restricted
(== network only for connections between host and guest machine) the
network access leantime became so slow it was barely usable anymore.
Even when I didn't restrict the network I had problems as the number of
containers seemed to increase every time I started the container with
docker run.

It would be really appreciated if you could provide simple instructions
for the casual linux user how to set this up locally in a safe way!

**Comment by gloriafolaron** [comment]
Thanks for your feedback here. I know having challenges setting something like this up can be really frustrating.

I'll start first: docker run should only be run once -- if you run it multiple times, you'll continue to create containers and thus slow down the system because all the containers are trying to run at one time. 

I'm not on the eng side here so it's harder for me to speak to the Linux installation but we do hear the feedback here. 

We've had some challenges in finding a way to cover for the many nuances that we see come up in our Discord groups (be sure to join here as well - many community members are able to help as well). 

Could you share a little more about your tool stack and around your experience as a "casual linux" user? That may help us with a frame of reference.
