### ISSUE TITLE
[FEATURE] Ability to edit comments

### ISSUE THREAD

**Issue by CodeShakingSheep** [Leantime/leantime#1873]
**Is your feature request related to a problem? Please describe.**
I would love to be able to edit comments. Sometimes it's necessary to correct typos or similar things.

**Describe the solution you'd like**
When clicking on the 3 dots of a comment I would like to have an entry "Edit" which lets you edit your own comment.
![image](https://github.com/Leantime/leantime/assets/19874562/b7fb068d-4de2-407e-890c-988be787af2c)

**Comment by DerKamii** [comment]
I don't know how long afterwards an edit is useful but i'd like to add to that feature addition with another feature:
marking comments as old / invalid / outdated.

Instead of editing old comments with new information, there might be the case where team members are dopped / deactivated and old comment's doesn't apply anymore but the active discussion is still relevant.
To avoid confusion one should be able to mark them as invalid / outdated so they get crossed out.

**Comment by CodeShakingSheep** [comment]
Editing comments is possible now. So, I'm closing this.
