### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RomainMendez** [Leantime/leantime#1907]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Random white pages being shown on Firefox (e.g when changing project, and all the time by clicking "Project Overview"

**To Reproduce**
1. Go to main screen
2. Change between projects until you get a white screen on "/dashboard/show"
OR 
1. Go to main screen
2. Go to Project Overview
3. See the white screen

**Expected behavior**
Not sure what is on the Project Overview normally

**Leantime Version**
v2.4-beta-3

**Server**
docker-compose on my own Ubuntu VM

**Additional context**
Just started trying to use the tool, maybe I should downgrade to 2.3.5.

**Comment by marcelfolaron** [comment]
Any errors in your logs/error.logs file ?

**Comment by jiriks74** [comment]
I've experienced this before too.
I once experienced one with project overview and it got fixed by modifying the project (bottom left corner).

When I was experimenting to fix some issues I noticed that I got a blank page when I forgot to add `;` to some lines.
I don't experience them anymore. (maybe because I updated Firefox?)
