### ISSUE TITLE
[BUG] Class "blade.compiler" does not exist

### ISSUE THREAD

**Issue by fabiorino** [Leantime/leantime#2102]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
Emails do not work. I run `leantime/bin/leantime email:test --address "myemailaddress@foobar.com`" to debug the issue, and the command errors with `Class "blade.compiler" does not exist`. 

I can fix the issue by hardcoding `$hideWrapper = true` at [this line](https://github.com/Leantime/leantime/blob/627d9232a6c4aec444419c8454ab50e5a2050f20/app/Core/Mailer.php#L188). This prevents the execution of `app('blade.compiler')::render` at [this line](https://github.com/Leantime/leantime/blob/627d9232a6c4aec444419c8454ab50e5a2050f20/app/Core/Mailer.php#L306C61-L306C76).

**Leantime Version**
2.4.7

**PHP / MySQL Version**
PHP 8.1

**Comment by jontorrado** [comment]
Hi there,

The `app/Core/Bootloader` file is not initializing the `Template` Core stuff, which includes that `blade.compiler`. When running this from the command line, Template is not initialized, so the `blade.compiler` does not exist.

Also, the right way (IMHO) to do this is with the `bind` method instead of the `singleton` method. But this is something that @marcelfolaron should take a better look at.

Cheers.
