### ISSUE TITLE
Mixed content behind nginx

### ISSUE THREAD

**Issue by Nixellion** [Leantime/leantime#231]
Hello, I'm trying to make Leantime docker image work with nginx reverse proxy using this config:

```
server {
	listen 80;
    server_name leantime.domain.com;
    return         301 https://$server_name$request_uri;


}

server {
        listen       443 ssl http2;
        listen       [::]:443 ssl http2;
        
        server_name leantime.domain.com;
        root /var/www/html;
        
        include defaults;
        
        location / {
            include proxy_params;
            proxy_pass http://10.10.0.4:8080;
            proxy_read_timeout 60s;
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
        }



    ssl_certificate /etc/.../fullchain.pem; # managed by Certbot
    ssl_certificate_key /.../privkey.pem; # managed by Certbot
}
```

But this way I don't get any resources like .js files loaded, because they are trying to load using 'http' and not 'https', and browsers block it. 

For example this file: `http://leantime.domain.com/js/compiled-app.min.js?v=2.1.0` wont download and is marked as blocked by webbrowsers.

Is it something I can fix from my end, or is it a bug?

**Comment by marcelfolaron** [comment]
Hey,

I just replied to the other issue as well. You can set the appURL when you
start the docker image

docker run -d -p 80:80 --network {some optional network} \
-e LEAN_DB_HOST=mysql_leantime \
-e LEAN_DB_USER=admin \
-e LEAN_DB_PASSWORD=321.qwerty \
-e LEAN_DB_DATABASE=leantime \
-e LEAN_APP_URL={yourdomain} \
--name leantime leantime/leantime:latest

**Comment by marcelfolaron** [comment]
Hey, just a follow up. Does it work with the new configuration?

**Comment by pomkos** [comment]
Hello,

I have a similar issue where nonsecure elements are not being loaded, see below.

![image](https://user-images.githubusercontent.com/8731022/80843342-15999080-8bd2-11ea-9965-53810c3d8a93.png)

I did try starting the container by defining app_url, however that led me to "leantime.domain.com/leantime.domain.com/install" instead of "leantime.domain.com/install". When I manually corrected it, I was able to finish the installation but nonsecure elements were still not loaded.

My setup: "leantime.domain.com" -> NGINX reverse proxy to docker container -> leantime container

My NGINX config file:

`server {

  server_name leantime.domain.com;
  root /var/www/html;
   
  location / {
      proxy_pass http://192.168.1.240:32770;
  }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/leantime.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/leantime.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = leantime.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot



  server_name leantime.domain.com;
    listen 80;
    return 404; # managed by Certbot


}
`

**Comment by marcelfolaron** [comment]
When setting the appURL please make sure to set the protocol. Eg
https://leantime.domain.com

The behaviour you described sounds like the https:// was missing

**Comment by pomkos** [comment]
That did the trick, thank you!

**Comment by dantefromhell** [comment]
> When setting the appURL please make sure to set the protocol. Eg
https://leantime.domain.com/

It would be great if https://github.com/Leantime/leantime/tree/master/config/sample.env mentions this, right now it states

> # Base URL, only needed for subfolder installation

**Comment by SkinnyT81** [comment]
Thanks for this thread.  It just sorted out my issue as well.
