### ISSUE TITLE
@mention with more then 10 user... missing someone?

### ISSUE THREAD

**Issue by twessman** [Leantime/leantime#2380]
**What set up are you using**
* [ ] Self Hosted

**Describe the bug**
We now have 11 active user, but the @mention list seems to not show a certain user now. Maybe it is capped at 10?

**To Reproduce**
1. Anywhere the @mention is supposed to work, 10 of our 11 users show up. The user is active and assigned to a project. (not certain if they post a comment anywhere yet but has been assigned something)

**Expected behavior**
All users, or better yet as you type @ it will sort/filter what is displayed to quickly select someone

**Leantime Version**
Was on 3.05, but just update 3.07 and still see it.

**Server**
Official docker image.

**Comment by rimi-itk** [comment]
It seems that we're using the default limit of 10 items (cf. https://github.com/StevenDevooght/tinyMCE-mention?tab=readme-ov-file#items). A higher limit can easily be set by defining `limit` in https://github.com/Leantime/leantime/blob/6635c4d3bb5b65adff5ea877eb6273b13784b0a9/public/assets/js/app/core/editors.js#L45-L76.

However, limiting to 10 items seems reasonable, and the real issue here might be that filtering in the underlying library, https://github.com/StevenDevooght/tinyMCE-mention, is broken and that Leantime therefore cannot (and doesn't) filter the user list based in the input (after `@`).

The solution seems to be hidden inside the pointers:

* https://github.com/StevenDevooght/tinyMCE-mention/issues/93#issuecomment-1853296121
* https://github.com/StevenDevooght/tinyMCE-mention?tab=readme-ov-file#items
* https://github.com/StevenDevooght/tinyMCE-mention/issues/1#issuecomment-22869442

I'll investigate further and try to come up with a solution.

**Comment by marcelfolaron** [comment]
Fixed in 3.1.0-beta
