### ISSUE TITLE
[FEATURE] Support for searching tickets by status type in API

### ISSUE THREAD

**Issue by rqi14** [Leantime/leantime#2533]
**Is your feature request related to a problem? Please describe.**
When calling the API for Tickets.getAll, there is an argument to set search criteria. It supports only the status code but not the status type. For example, if I would like to search all tickets that have a status type of INPROGRESS, I cannot do that. Searching for status code is less useful because it could have various meanings across projects. I tried to loop through all projects and retrieving status labels then I hit rate limit.

**Describe the solution you'd like**
Please allow searching for status types in `$searchCriteria`

**Additional context**

**Comment by VLNTNO** [comment]
Hello,
Thank you for your ticket because thanks to it I could figure out which parameter to provide to the JSON payload to have this method to work.

However, the `status code` parameter which you mention does not exist (or doesn't anymore).
Instead, the `status type` parameters actually exists.
Here is an example of the payload I used to obtain a successful response containing the list of the tickets with status type `NEW`:

    {
        "method": "leantime.rpc.Tickets.Tickets.getAll",
        "jsonrpc": "2.0",
        "id": 1,
        "params": {
            "searchCriteria": {
                "statusType": "NEW"
            }
        }
    }
 
Therefore I think you can close your feature request since it seems fulfilled.

Regards
Valentin

**Comment by rqi14** [comment]
Thanks!
