### ISSUE TITLE
[FEATURE] Allow SVG format for project avatar

### ISSUE THREAD

**Issue by pablopoo** [Leantime/leantime#2574]
**Is your feature request related to a problem? Please describe.**
Allow SVG format for project avatar

**Describe the solution you'd like**
add .svg to allowed image formats. Is not listed currently, but is supported.

**Additional context**
--

**Comment by marcelfolaron** [comment]
An updated on this issue: We supported svg avatars for a bit and found that it creates too much of a security risks since svg graphics can include javascript which will be executed. 
The only viable option for this problem seems to be to host these images on a separate subdomain/domain which is what wikipedia does for example. As this is not feasible we decided to stop supporting svg avatars.
