### ISSUE TITLE
[Bug]: Plugins no longer utilize user as api authentication

### ISSUE THREAD

**Issue by jeppekroghitk** [Leantime/leantime#2819]
### What is your set up?

Self Hosted Docker

### Version

3.3.2

### Describe the issue

Upon calling the API via javascript, previously the api call were on the behalf of the authenticated user. Now i get 

{
    "error": "Invalid API Key"
}

when calling (via javascript when logged into my account)

{
    "method": "leantime.rpc.tickets.getAll",
    "jsonrpc": "2.0",
    "id": "1",
    "params": {}
}

### Reproduction steps

1. Call api via javascript while logged in

### Additional Notes

@marcelfolaron im not quite sure if this is newly introduced intended behaviour or a bug.

**Comment by marcelfolaron** [comment]
Hey, just to confirm: 
Are you using the jsonrpc api as the user who us currently logged in (regular session), without x-api-key in the header? 

If so, that is an interesting use case that I had not intended originally, so if that was working before that was not on purpose. With that said I can see how that is actually quite useful. 

The reasons this is not working anymore is that I updated our middleware to either use the regular auth flow or the API auth flow which only authenticates via x-api-key. 

Let me take a look again because I made some assumptions about the session states for api users and the length of their sessions which could have other side effects.

**Comment by jeppekroghitk** [comment]
@marcelfolaron Yes, without the x-api-key header. 

It has been useful when writing plugins, since the authentication part is already taken care of since you're logged in. 

I think it would be cool to keep this "functionality", in the case the api is called from a plugin (Or i guess when there is a user stored in session). 

It's up to you, just please let me know what way you end up going, because im going to need to make some changes in our plugins if the x-api-key header is going to be required. 

Nevertheless, thanks for taking a look at it again.
