### ISSUE TITLE
[BUG] Deleting an Idea Board hides ideas in another board

### ISSUE THREAD

**Issue by nikolasj5** [Leantime/leantime#288]
**Describe the bug**
Inside the same projetct, when you have two idea boards and deletes one of them the ideas in the other idea board are hidden. If you create a new idea board they are shown again.

**To Reproduce**
1. Go to Ideas having two filled idea boards 
2. Click on Delete Board and confirm
3. The remaining idea board will be blank

**Expected behavior**
The ideas in the remaining board should display.

**Leantime Version**
2.1.4

**Server**
nginx

**PHP / MySQL Version**
PHP 7.3
psql (PostgreSQL) 12.1 (Debian 12.1-1.pgdg100+1)

**Additional context**
Google Chrome Version 83.0.4103.97

**Comment by marcelfolaron** [comment]
Thanks for the report, I'll take a look tomorrow.

**Comment by kimberely27** [comment]
Add just before Line 32  src/domain/ideas/controllers/class.delCanvas.php
`                $tpl->setNotification($language->__("notification.idea_board_deleted"), "success");
                $tpl->redirect(BASE_URL."/ideas/showBoards");`
`				unset($_SESSION['currentIdeaCanvas']);
                $tpl->setNotification($language->__("notification.idea_board_deleted"), "success");
                $tpl->redirect(BASE_URL."/ideas/showBoards");`

The problem is that it keeps the Session active and it won't show the correct Canvas ID Ideas plus if you add a new Idea it will save in the already deleted Canvas ID.
