### ISSUE TITLE
[BUG] Reports not working when sprint is created.

### ISSUE THREAD

**Issue by stormrage-project** [Leantime/leantime#293]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
When I want to display 'Reports' the page is blank. The Apache2 error.log is showing the following error:

[Thu Jun 18 08:02:53.973031 2020] [php7:error] [pid 31194] [client 192.168.102.1:55225] PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (16/06/2020) at position 0[...] and so on

**To Reproduce**
1. Go to 'To-Dos', create a new sprint
2. Click on 'Reports' -> white/blank Page
3. When you delete the Sprint, 'Reports' is working as expected again.

**Expected behavior**
'Reports' should work wether there are sprints or not.

**Leantime Version**
2.1.4

**Server**
Apache2

**PHP / MySQL Version**
PHP: v7.2.24-0ubuntu0.19.04.1
mysql:  Ver 15.1 Distrib 10.3.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by gerickt** [comment]
Same error here, http error 500 after create a new sprint

**Comment by RubaiyatOZ** [comment]
> 
> 
> Same error here, http error 500 after create a new sprint

In my case I don't get an error 500, just a blank page. This started after I created a new Sprint.

**Comment by nikolasj5** [comment]
Same with me and I get a error 500.

**Comment by JulioSM98** [comment]
Solution: In www/html/src/domain/sprints/services/class.sprints.php
![image](https://user-images.githubusercontent.com/29544449/142424305-34e8fdf8-bfba-4d4e-8469-56013c9d9782.png)
And
![image](https://user-images.githubusercontent.com/29544449/142424347-4ad1a1f0-4dc1-471a-9f6c-cef3039494fd.png)
other Solucion for report Get all:
In www/html/src/domain/reports/controllers/class.show.php
![image](https://user-images.githubusercontent.com/29544449/142424488-5b068bb2-bcb5-480c-96b7-02e1ad2861f9.png)
Delete Else

**Comment by nicopdy** [comment]
I still have the same issue in the 2.1.8 version

**Comment by jallen127** [comment]
Starting using Leantime today. If your using language en-GB its because the dd/mm/yy format can't be converted using PHP DateTime in 'function getSprintBurndown()'
A work around in 2.1.8 would be to change this:
`$sprint->startDate = $this->language->getFormattedDateString($sprint->startDate);
 $sprint->endDate = $this->language->getFormattedDateString($sprint->endDate);`
to
`$sprint->startDate = $sprint->startDate;
 $sprint->endDate = $sprint->endDate;`
It solves that report issue but I haven't looked into what other implications that may have so try at your own risk
