### ISSUE TITLE
No database connection.

### ISSUE THREAD

**Issue by Valiantiam** [Leantime/leantime#324]
php 7.3
mysql 8
debian 10

trying to find out why after confirming db credentials (and logging in manually) I am still getting 
"No database connection, check your database credentials in your configuration file."
when I go to mydomain.com/install.

I can confidently say my credentials are 100% correct. mysql db is also on the local host.

**Comment by marcelfolaron** [comment]
What host URL are you using? We noticed that in some cases it won't work with "localhost"

**Comment by erindru** [comment]
This just happened to me. Its hard to debug because the constructor of the db class in 'src/core/class.db.php' swallows exceptions. I modified it to print the exception.

In my case, the issue was caused by the error "The server requested authentication method unknown to the client [caching_sha2_password]" which is the result of MySQL 8.0's upgrade to use a more secure authentication mechanism.

Fixing it was a matter of switching the leantime user to use legacy authentication, eg:

```
alter user 'leantime'@'%' identified with mysql_native_password by '<new password>';
```
