### ISSUE TITLE
[FEATURE] possibility for admin to set user passwords. 

### ISSUE THREAD

**Issue by LightTemplar** [Leantime/leantime#334]
I have created some users a while ago and have forgotten their passwords. I would like to set them new passwords, but there is no such functionality in the user management.

**Comment by tiredofit** [comment]
This would be very useful. I am in a same situation where a user has forgotten their password and is not receiving the password reset emails and has since locked themselves out from being able to reset their password with "You have reached the password reset limit for your account, please use the last reset link to reset your password"

**Comment by carsteneu** [comment]
I wrote a fix for that... took a few minutes und fixed a bug by the way ;-) https://github.com/Leantime/leantime/pull/337

**Comment by marcelfolaron** [comment]
Hey, 

Thanks all. I'll check the PR today and will merge!

**Comment by NoobTW** [comment]
This should be closed.
