### ISSUE TITLE
[BUG] - User update without password puts an empty password with possible login

### ISSUE THREAD

**Issue by GhaziTriki** [Leantime/leantime#427]
**Describe the bug**
When a user is updated without setting it is password it puts an empty password. The user is then able to login with an empty password.

**To Reproduce**
1. Update a user profile in "Users Management"

**Expected behavior**
The password update should be ignored if provided empty. The user must never be able to login with an empty password.

**Leantime Version**
2.1.7

**Server**
nginx

**PHP / MySQL Version**
PHP 7.4, MariaDB 5.7

**Comment by aarchijs** [comment]
The same issue as #416 and #412

Hopefully developer will solve this. Because this is a security issue.  Anyone with admin rights can reset other user password and do something with other user account contents without their consent. 
Or reset password to blank by accident and then anyone with access to this server can do the same.

**Comment by trinhpc** [comment]
Anyupdate, please ?

**Comment by CdiegoBB** [comment]
@trinhpc  go to the issue #412
