### ISSUE TITLE
Link to Google docs in the description breaks kanban layout

### ISSUE THREAD

**Issue by stantum** [Leantime/leantime#561]
**Describe the bug**
Insert a link to a spreadsheet on google docs into a task description. The link must be formatted as an url. Kanban board is getting destroyed. 

**Leantime Version**
2.1.8

**Server**
nginx

**PHP / MySQL Version**
PHP 7.4, MariaDB 10.4

![](https://user-images.githubusercontent.com/75078793/148757202-a9d154fe-c035-4dee-ba9f-839cf140a588.png)

**Comment by x2zdigital** [comment]
noticing a similar issue with overly long titles / descriptions.  This could be quickly fixed with css??

**Comment by marcelfolaron** [comment]
Yeah, that is an overflow issue. Simple css rule should fix that. We just
need to make sure to allow vertical overflow so you can still scroll within
a column

**Comment by x2zdigital** [comment]
I would propose a user controlled setting specifying a number of title lines to be shown, maybe 3?   I dont agree with adding scrollbars, they take up too much space on smaller screens and add to overall clutter.   A better overall solution would be to load the complete task view/edit data dynamically and show it in a popover instead of the current page load.  This would give enough initial information while keeping the data load to a minimum while allowing quick access to the complete card.  Thoughts?
