### ISSUE TITLE
[FEATURE] Allowing other users to see my calendar.

### ISSUE THREAD

**Issue by pv-misab** [Leantime/leantime#572]
Is it possible to let other users know about my schedule. Whenver I add any event or to-do, it shows up in a calendar where others can see what I am working on that day.

**Comment by RossBeagle2** [comment]
I was looking for something similar, so I created a work-around. If you're happy for ALL calendar events to be visible by ALL users (essentially creating a global shared calendar), then you can take out the WHERE clause in the database query where it searches for only your calendar events.

Open up /src/domain/calendar/repositories/class.calendar.php
Go to line 33/34 and remove WHERE userId = :userId
Comment out line 37 (where the userId is added into the prepared statement

This works for normal calendar entries. If you want something similar for to-dos as well (i.e. ALL users see ALL to-dos), then something similar can be done with the 'tickets' database query - remove both parts of the WHERE clause which mention userId on line 58 (the bit in brackets, plus the 'AND' after it) and comment out line 61.

I have done both of these because I wanted all tasks and calendar entries to be visible to everyone as we have shared goals and we'll be using the calendar entries to know when people are going to be out of the office or unavailable.

**Comment by pv-misab** [comment]
Thanks for this
