### ISSUE TITLE
Fix users with 0 projects issues

### ISSUE THREAD

**Issue by ss3844** [Leantime/leantime#61]
I also use docker image to create leantime project.  When I use admin to create a manager account, I got an error at this. What can I do in this error?

Notice: Undefined offset: 0 in /var/www/html/src/core/class.frontcontroller.php on line 90

Notice: Undefined offset: 0 in /var/www/html/src/core/class.frontcontroller.php on line 91

Notice: Undefined offset: 0 in /var/www/html/src/core/class.frontcontroller.php on line 92

**Comment by marcelfolaron** [comment]
Hey, thanks for filing. 

It seems that there isn't a default project in your system, that should have been created during installation? When do you see the notices? Is that when you create a new user? 

This should only happen if you don't have any projects assigned to yourself.
The easiest way to get around that would be to create a project under <youdomain>//projects/newProject/

In the meantime I'll make sure to catch that error case. This will be fixed in the next release.

**Comment by ss3844** [comment]
Thank you for the prompt support.

I see this error message when I create a new user and doesn't have any project in system. When I create a default project for him, the error message will be solved.

**Comment by marcelfolaron** [comment]
Thank you for confirming that. I'll make sure to include a fix in the next release which will be 2.1
