### ISSUE TITLE
1071 Specified key was too long on install

### ISSUE THREAD

**Issue by emanuelfreitas** [Leantime/leantime#68]
Hello,

I was trying to install Leantime (v2.0.3) using the docker image but I'm getting the following error:

```
Something went wrong
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Before continuing you should delete all tables from your database.
```

![Screen Shot 2019-12-07 at 15 47 30](https://user-images.githubusercontent.com/4059176/70377224-ba58c000-1909-11ea-84a1-4a252b468524.png)

All the fields that I'm inserting are very small, they are far from 767 bytes.

There are no errors on the logs.

**Comment by marcelfolaron** [comment]
Hi,
I'll take a look. Which MySQL version are you using?

**Comment by marcelfolaron** [comment]
Thanks for reporting the bug. The problem was the utf8mb4 definition in our docker readme file when creating a MySQL container. We updated our installation (https://github.com/Leantime/leantime/pull/69) script to force utf8 usage until we can migrate all tables to utf8mb4. In the meantime please create a new MySQL container using the collation as described in: https://github.com/Leantime/docker-leantime

A new release will be cut tomorrow.
