### ISSUE TITLE
ARM64

### ISSUE THREAD

**Issue by leornt** [Leantime/leantime#770]
Docker image doesn't have arm64 support, could you please add it?
Think dockerx could be used to it
Also, `mysql:5.7` can turn into `mariadb` for better arch support

**Comment by phulstaert** [comment]
Although MariaDB is a fork of MySQL, there are differences between them.
I would rather support the idea of moving to MySQL:8.0 (that has arm64 support) rather then going to MariaDB and risk worse performance due to another query optimizer.  (agreed that this is almost never the case - knowing that I personally use MariaDB for almost every project I do; but since we use MySQL now, switching is a bigger thing then updating to the next version of MySQL).

I would be nice to see qslite. This would make the docker instance far less memory intensive. sqlite has a bad name since it is file based, but it is almost all the time as performant as their "big brothers" and kan go up to tables in the TB's.

FYI: The currently used php 8.0.12 has arm/v5 support.

**Comment by S0und** [comment]
Thank you for the arm64 docker image!
