### ISSUE TITLE
Can not log in 

### ISSUE THREAD

**Issue by adnredwan77** [Leantime/leantime#81]
Hi, I've created the database from class.install.php file, I copied the create statements and run it on the database , after that copy the insert statments and run it on the database one by one
and change the parameters with suitable values,
I've inserted user in zp_user table
and try login but it fails also

**Comment by marcelfolaron** [comment]
Hey I assume you left the password field blank? Passwords are stored using the 
`password_hash()` function. You could try to reset your password under /resetPassword
Based on the previous thread though you might not get to that page due to htaccess not set up. 

You'd have to make sure that is working first since Leantime depends on those rewrites.

Are you running apache or nginx?

**Comment by marcelfolaron** [comment]
Closing this for now. Let me know if you run into any other issues.
