### ISSUE TITLE
[BUG] - /install doesn't work in browser

### ISSUE THREAD

**Issue by wandisuh0887** [Leantime/leantime#987]
Hello,

i have problem when installing(production) leantime on server, /install can't run in browser. I have also followed the steps in the instructions.

i am using nginx and php 8
root /var/www/leantime/public

Can anyone explain?
many thanks

**Comment by calawhkbu** [comment]
> Hello,
> 
> i have problem when installing(production) leantime on server, /install can't run in browser. I have also followed the steps in the instructions.
> 
> i am using nginx and php 8 root /var/www/leantime/public
> 
> Can anyone explain? many thanks

Can you describe which branch did you install (master / stable) 
Can you show a screenshot of your browser?
Can you show us the /public/.htaccess file 
If possible please list the files in  using the (ls) command

-  root /var/www/leantime/public
- root /var/www/leantime

**Comment by marcelfolaron** [comment]
Also which nginx config are you running? What error message do you see in
your browser (500 or 404) and then the contents of resource/logs/error.log

**Comment by jupiter126** [comment]
Same issue, 
Fresh install of latest "release" (hence stable I guess) on ubuntu 22.04 , using nginx mariadb php8.1

The file called "install" is not in /public/ , triggering a 404
/var/leantime# ls -a
.  ..  .htaccess  .idea  CODE_OF_CONDUCT.md  CONTRIBUTING.md  LICENSE  README.md  SECURITY.md  config  nginx-subfolder.conf  nginx.conf  public  resources  src  userfiles  vendor

/var/leantime# ls -a public/
.  ..  .htaccess  backup.php  cron.php  css  download.php  fonts  images  index.php  js  less  userfiles

When heading to domain.com/install, I get the 404.
When heading to domain.com/index.php, I'm forwarded to the domain.com/install and also get a 404.

**Comment by calawhkbu** [comment]
> resource/logs/error.log

Please kindly post your Error Log 
In order to debug please try the following

-  Create an index.html
-  Type the following content 
- <html><body>testing</body></html>
- Save 
- Navigate to <domain.com>/
- Do you see the testing Text?


Verify that you have ngix installed and running?
- service nginx status 
- service apache2 status 
- print screen or show us the logfile

- 

[Background]
I hace assumed you have done the following 
- Install composer 
- Install npm
- install grunt ( css, js files) 

Please show us the ngix.conf file 
Are the settings as follows ?

```
  set $base /var/leantime;
  root $base/public;
```


In this application
<domain.com> will default look for index.html / index.php 
 There is a .htaccess (apache2) or ngix.conf -> which determines where to start, in this case start reroute all / traffic to public/ 

public/ implies it will look for index.html / index.php 
public/index.php exist
public/index is rewritten as     rewrite ^(.*)$ /index.php?install=true;
The install.php locates in /src/install.php 
public/index.php L31 $application->start();
The start function is defined in /src/core/class.application.php
install was a hardcoded page 

```
   //Hard coded routes for a few pages that can be access without login
            if(isset($_GET['resetPassword']) === true) {
                include '../src/resetPassword.php';
            }else if(isset($_GET['install']) === true) {
                 include '../src/install.php';
            }else if(isset($_GET['update']) === true) {
                include '../src/update.php';
            }else{
                include '../src/login.php';
            }   
```

**Comment by calawhkbu** [comment]
> Same issue, Fresh install of latest "release Leantime-v2.2.7.tar.gz" (hence stable I guess) on ubuntu 22.04 , using nginx mariadb php8.1
> 
> The file called "install" is not in /public/ , triggering a 404 /var/leantime# ls -a . .. .htaccess .idea CODE_OF_CONDUCT.md CONTRIBUTING.md LICENSE README.md SECURITY.md config nginx-subfolder.conf nginx.conf public resources src userfiles vendor
> 
> /var/leantime# ls -a public/ . .. .htaccess backup.php cron.php css download.php fonts images index.php js less userfiles
> 
> When heading to domain.com/install, I get the 404. When heading to domain.com/index.php, I'm forwarded to the domain.com/install and also get a 404.

> resource/logs/error.log

Please kindly post your Error Log 
In order to debug please try the following


usually html files are put in /var/www/index.html 
I see you put files in /var/leantime, 
may i know why did you do this? 
did you made alterations to the original nginx server ? 


-  Create an index.html
-  Type the following content 
- <html><body>testing</body></html>
- Save 
- Navigate to <domain.com>/
- Do you see the testing Text?


Verify that you have ngix installed and running?
- service nginx status 
- service apache2 status 
- print screen or show us the logfile

- 

[Background]
I hace assumed you have done the following 
- Install composer 
- Install npm
- install grunt ( css, js files) 

Please show us the ngix.conf file 
Are the settings as follows ?

```
  set $base /var/leantime;
  root $base/public;
```


In this application
<domain.com> will default look for index.html / index.php 
 There is a .htaccess (apache2) or ngix.conf -> which determines where to start, in this case start reroute all / traffic to public/ 

public/ implies it will look for index.html / index.php 
public/index.php exist
public/index is rewritten as     rewrite ^(.*)$ /index.php?install=true;
The install.php locates in /src/install.php 
public/index.php L31 $application->start();
The start function is defined in /src/core/class.application.php
install was a hardcoded page 

```
   //Hard coded routes for a few pages that can be access without login
            if(isset($_GET['resetPassword']) === true) {
                include '../src/resetPassword.php';
            }else if(isset($_GET['install']) === true) {
                 include '../src/install.php';
            }else if(isset($_GET['update']) === true) {
                include '../src/update.php';
            }else{
                include '../src/login.php';
            }   
```

**Comment by jupiter126** [comment]
Error log is empty.
I moved created a specific /var folder for leantime so that it wouldn't be mixed with another website.
Didn't alter the nginx server, only the config (as per vhosts requires).
Tried both with a minimal working conf, and with the provided (modified) nginx.conf
My minimal file reads as:
``` 
  server {
    server_name projets.exampledomain.com;
    access_log /var/log/nginx/projets.access.log;
    root /var/leantime/public;

       location ~ \.php$ {
	include snippets/fastcgi-php.conf;
	fastcgi_pass unix:/run/php/php8.1-fpm.sock;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/projets.exampledomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/projets.exampledomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
  server {
    if ($host = projets.exampledomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name projets.exampledomain.com;
    listen 80;
    return 404; # managed by Certbot

}
```

Yes, nginx is running and serving demo html/php on that vhost.
No, I didn't install composer/grunt/npm, I didn't see mention of them in install docs.
config is done in php, and db created with required rights/user/pw

Still no install, and when I call index.php?install=true, I get a failing redirect to https://projets.exampledomain.com/install/update

I managed to hit https://projets.exampledomain.com/install/update/install by mistake while forging the url, filled in the fields, but then got hit by another redirection error to https://projets.exampledomain.com/install/update as soon as I click a button.

**Comment by calawhkbu** [comment]
May I suggest you install using the stable version 2.0.14 ? 



> Error log is empty. I moved created a specific /var folder for leantime so that it wouldn't be mixed with another website. Didn't alter the nginx server, only the config (as per vhosts requires). Tried both with a minimal working conf, and with the provided (modified) nginx.conf My minimal file reads as:
> 
> ```
>   server {
>     server_name projets.exampledomain.com;
>     access_log /var/log/nginx/projets.access.log;
>     root /var/leantime/public;
> 
>        location ~ \.php$ {
> 	include snippets/fastcgi-php.conf;
> 	fastcgi_pass unix:/run/php/php8.1-fpm.sock;
>         }
> 
>     listen 443 ssl; # managed by Certbot
>     ssl_certificate /etc/letsencrypt/live/projets.exampledomain.com/fullchain.pem; # managed by Certbot
>     ssl_certificate_key /etc/letsencrypt/live/projets.exampledomain.com/privkey.pem; # managed by Certbot
>     include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
>     ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
> 
> }
>   server {
>     if ($host = projets.exampledomain.com) {
>         return 301 https://$host$request_uri;
>     } # managed by Certbot
> 
>     server_name projets.exampledomain.com;
>     listen 80;
>     return 404; # managed by Certbot
> 
> }
> ```
> 
> Yes, nginx is running and serving demo html/php on that vhost. No, I didn't install composer/grunt/npm, I didn't see mention of them in install docs. config is done in php, and db created with required rights/user/pw
> 
> Still no install, and when I call index.php?install=true, I get a failing redirect to https://projets.exampledomain.com/install/update
> 
> I managed to hit https://projets.exampledomain.com/install/update/install by mistake while forging the url, filled in the fields, but then got hit by another redirection error to https://projets.exampledomain.com/install/update as soon as I click a button.

**Comment by jupiter126** [comment]
Tried stable 2.0.14 and commented out to same results.

**Comment by calawhkbu** [comment]
> Tried stable 2.0.14 and commented out to same results.

I am guessing its the problem of nginx.conf

How about trying to replace the original 
nginx.conf and nginx-subfolder.conf
Source  https://github.com/Leantime/leantime/blob/master/nginx-subfolder.conf

Alternative Solution,
Install Apache2 to run the leantime application

**Comment by marcelfolaron** [comment]
The minimal nginx config you have listed won’t work. You need at least the
redirects from the example nginx. Everything else looks good to me.

**Comment by marcelfolaron** [comment]
PS don’t use 2.0.14. There were a lot of updates to routing and url
handling in the follow up versions

**Comment by andersonblaine** [comment]
Last commit 9121f41 (https://github.com/Leantime/leantime/commit/9121f41b37271bb3e470e47085091cbc77aa955a) solved the problem. Thanks!

**Comment by jupiter126** [comment]
In my case, setting the redirects didn't help (including 9121f41)
