### ISSUE TITLE
LDAP on Active Directory not functional

### ISSUE THREAD

**Issue by compumatter** [Leantime/leantime#993]
**Describe the bug**
Cannot login via LDAP using Active Directory

**To Reproduce**
Using AD  username and password do not grant access. 

**Expected behavior**
Should login

**Leantime Version**
2.2.7

**Server**
NGINX

**PHP / MySQL Version**
8.1 / 5.7.4

**Additional context**
I am paying a high level LDAP developer to configure this software assuming it was my configuration mistake.  He is confirming that this is a problem with the code and not with the LDAP config.  I think it would be my contribution to your great software to pay him to work directly with you and code the fix for this.  I have downloaded our thread on upwork.com so you may have a look at this and hopefully engage.  This is an opportunity for both of us and the community of users to resolve this for all our benefits:

- https://compumatter.com/tmp/upwork-thread.php

We are using Samba 4 AD which responds to queries exactly as Microsoft AD.   Samba 3 was the last Samba version to use OpenLDAP.   OpenLDAP is now a deprecated platform for Samba. They now use the Microsoft AD as the default protocol.  I have it configured properly in Leantime but is failing.  So I expect all Microsoft LDAP uses will have the identical problem.

**Comment by compumatter** [comment]
We may have a resolution in place for this.  The dev and I found something today.  Will advise.

**Comment by marcelfolaron** [comment]
Thank you for your help on that!

**Comment by compumatter** [comment]
The program is worth effort.  You are welcome.  Question here.  Is there a quick method to clear any remembered session data.  I feel session login data is possibly giving us some mixed results on attempts as we switch to various settings to test.

**Comment by marcelfolaron** [comment]
easiest way is to delete the local session cookie in your browser.

**Comment by compumatter** [comment]
My dev believes that the configuration information contained in configuration.php is being cached in some way.  He changes it but does not see the results or at some point sees results inconsistent with the current configuration file.   Can you think of anything within the code that would cause this so we can disable it?   See his notes:
![image](https://user-images.githubusercontent.com/121611/192158079-69895512-b5e1-4c31-b83b-dee898fd57bd.png)

**Comment by marcelfolaron** [comment]
Hi, yes. You can add

`unset($_SESSION['mainconfig'][$envVar])`

Into the configuration file at the beginning of the `
configEnvironmentHelper` method.

That will ensure the chache is not being used.

Sincerely,
Marcel

**Comment by compumatter** [comment]
This issue is resolved.  The main problem was LDAP configuration caching.  Somehow wrong LDAP configs were cached and testing with different settings were ignored.  That left us in a situation where we could never get a direct cause / effect to insure we had the right information in configuration.php.  This took our dev many, many hours of testing before it was clear the configs were being ignored through caching.  Browser cache was of course cleared but the problem is session caching.

Our recommendation is not use caching for LDAP configs.  Other users will surely have this problem.  It is common for applications requirements for LDAP to be different than one other due to naming conventions.   At the very least a feature for $cache_ldap_configs=false to allow it to be overridden.

Thanks.

**Comment by Mrs-Feathers** [comment]
i'm on version 2.3.27 and having trouble with this as well. LDAP settings are confirmed correct, getting login success messages in logs/error.log but "incorrect account" on the login screen ever since we tried to move from one LDAP server to our new "Authentik" database. this issue looks like the exact one i'm having but not able to figure out where to add the "unset" code as there isnt a "configEnvironmentHelper" line in the configuration.php file

**Comment by compumatter** [comment]
I am using version 2.3.25 and all is well with LDAP in a Linux Samba 4 AD DC environment.

**Comment by Mrs-Feathers** [comment]
yes, i found out my specific issue was due to a small bug in a hotfix directly before the update. i dont think it effects anyone else because afaik it was just myself and one other person testing it late at night before 2.3.25 was official.. but i was able to remove the offending line and it works absolutely perfectly! i switched from AD to LDAP and while the bug seemed to work just fine on AD, it didn't like i tried to configure LDAP (along with the config is cached and i didn't know that, so i had to figure out how to clear the cache before each time i tested. but i eventually figured it out and like i said, it works perfect now. entire database migrated with zero data loss!)
